# Generated by Django 4.2.8 on 2023-12-11 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='lastname',
            new_name='num',
        ),
    ]
