# Generated by Django 4.2.8 on 2023-12-13 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_lastname_member_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='notes',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
