# Generated by Django 4.2.8 on 2023-12-13 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_member_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='time_now',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
