# Generated by Django 4.2.8 on 2023-12-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_member_time_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='time_now',
        ),
    ]
