# Generated by Django 4.2.8 on 2023-12-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_member_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='created_at',
            new_name='createdTime',
        ),
    ]
