# Generated by Django 4.2.8 on 2023-12-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_rename_created_at_member_createdtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
