# Generated by Django 4.2.8 on 2023-12-14 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_member_createdtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
