# Generated by Django 4.2.8 on 2023-12-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_alter_member_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
    ]
